PLATFORM = Web
ARCH = wasm
TARGET_TYPE = a
MIDI_API = __WEB_MIDI_API__

EM_DIR := $(shell ls -1d /Applications/Unity/Hub/Editor/*/PlaybackEngines/WebGLSupport/BuildTools/Emscripten 2>/dev/null | sort -V | tail -1)

export EM_CONFIG := $(EM_DIR)/.emscripten

BIN_PATH = $(EM_DIR)/emscripten
CC = $(BIN_PATH)/emcc
AR = $(BIN_PATH)/emar

include Common.mk
