PLATFORM = Android
ARCH = arm64
TARGET_TYPE = so
MIDI_API = __AMIDI__

BIN_PATH = $(ANDROID_NDK_ROOT)/toolchains/llvm/prebuilt/darwin-x86_64/bin
CC = $(BIN_PATH)/aarch64-linux-android30-clang++

CCFLAGS = -fPIC
LDFLAGS = -shared -Wl,-z,max-page-size=16384
LIBS = -static-libstdc++ -lamidi

include Common.mk
