PLATFORM = iOS
ARCH = arm64
TARGET_TYPE = a
MIDI_API = __MACOSX_CORE__

SDK = iphoneos
SDK_MIN_VER = 12.0

CC := $(shell xcrun --sdk $(SDK) -f clang++)
SYSROOT := $(shell xcrun --sdk $(SDK) --show-sdk-path)

CCFLAGS += -target $(ARCH)-apple-ios$(SDK_MIN_VER) -miphoneos-version-min=$(SDK_MIN_VER)
CCFLAGS += --sysroot $(SYSROOT) -isysroot $(SYSROOT) -fembed-bitcode

include Common.mk
